apiVersion: v1
kind: Service
metadata:
  name: server-one-lb
  namespace: garden
  labels:
    app: server
    role: test
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: api
  selector:
    app: server
    role: test
  type: LoadBalancer
