apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-logging
    role: logging
  name: elasticsearch-logging
  namespace: <NAMESPACE>
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
  selector:
    app: elasticsearch-logging
    role: logging
  sessionAffinity: None
  type: ClusterIP
