#apiVersion: autoscaling/v1
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fluentd-es
  namespace: garden
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: fluentd-es
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
