apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: fluentd-es
    role: logging
  name: fluentd-es
  namespace: garden
spec:
  selector:
    matchLabels:
      app: fluentd-es
      role: logging
  serviceName: fluentd-es
  template:
    metadata:
      labels:
        app: fluentd-es
        role: logging
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fluentd-es
              - key: role
                operator: In
                values:
                - logging
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env: 
        - name: FLUENTD_ARGS
          value: "--workers=16 -v"
        image: eu.gcr.io/gardener-project/gardener/fluentd-es:0.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 24224
          periodSeconds: 5
          timeoutSeconds: 2
          initialDelaySeconds: 5
          # periodSeconds: 30
          # timeoutSeconds: 10
          # initialDelaySeconds: 30
        name: fluentd-es
        ports:
        - containerPort: 24224
          name: fwd-input
          protocol: TCP
        - containerPort: 24224
          name: fwd-input-udp
          protocol: UDP
        resources:
          limits:
            cpu: 700m
            memory: 3200Mi
          requests:
            cpu: 450m
            memory: 3000Mi
        volumeMounts:
        - mountPath: /etc/fluent/config.d
          name: config-volume
        - mountPath: /gardener/flentd-buffers
          name: fluentd
      serviceAccount: fluentd-es
      serviceAccountName: fluentd-es
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: fluentd-es-config
        name: config-volume
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: fluentd
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
