apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-lb
  namespace: garden
  labels:
    app: elasticsearch-logging
    role: logging
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
  selector:
    app: elasticsearch-logging
    role: logging
  type: LoadBalancer
